In [234]:
import numpy as np
#Node_State = np.array([[1,0,3],[4,2,5],[7,8,6]]) #working_instant
#Node_State = np.array([[2,8,3],[1,6,4],[7,0,5]]) #takes_lot_of_time
#Node_State = np.array([[2,4,3],[7,8,0],[6,1,5]])  #working_maybe_a_min
Node_State = np.array([[1,0,2],[4,6,8],[7,3,5]]) #working_instant
#Node_State = np.array([[4,8,1],[5,2,0],[7,6,3]]) #working_instant
#Node_State = np.array([[7,2,3],[1,5,6],[4,8,0]]) #working_maybe_a_min



Goal_Node = np.array([[1,2,3],[4,5,6],[7,8,0]])
ParentNodes = {}
ParentNodes = {1:0}
AllNodes ={}
AllNodes = {1:Node_State}
path = list()

NewNode1 = Node_State.copy()
NewNode2 = Node_State.copy()
NewNode3 = Node_State.copy()
NewNode4 = Node_State.copy()

a = 1
b = 1
next_node =1
flag = 1
clean =1


In [212]:
[i,j] = BlankTileLocation(Node_State)

In [213]:
[i,j]

[1, 2]

In [214]:
def BlankTileLocation(state):
    for i in range(0,len(Node_State[1])):
        for j in range(0,len(Node_State[1])):
            if state[i,j] == 0:
                return[i,j]
            
            
def ActionMoveLeft(state):
    New_state = state.copy()
    for i in range(0,len(New_state[1])):
        for j in range(0,len(New_state[1])):
            if state[i,j] == 0:
                if j == 0:
                    print("cannot perform left movement")
                    return[0, state]
                else:
                    print("left movement performed")
                    New_state[i,j-1], New_state[i,j] = New_state[i,j], New_state[i,j-1]
                    return[1, New_state]
            
            
def ActionMoveRight(state):
    New_state = state.copy()
    for i in range(0,len(New_state[1])):
        for j in range(0,len(New_state[1])):
            if state[i,j] == 0:
                if j == 2:
                    print("cannot perform Right movement")
                    return[0, state]
                    
                else:
                    print("right movement performed")
                    New_state[i,j+1], New_state[i,j] = New_state[i,j], New_state[i,j+1]
                    return[1, New_state]

def ActionMoveUp(state):
    New_state = state.copy()
    for i in range(0,len(New_state[1])):
        for j in range(0,len(New_state[1])):
            if state[i,j] == 0:
                if i == 0:
                    print("cannot perform Up movement")
                    return[0, state]
                    
                else:
                    print("up movement performed")
                    New_state[i-1,j], New_state[i,j] = New_state[i,j], New_state[i-1,j]
                    return[1, New_state]
            
def ActionMoveDown(state):
    New_state = state.copy()
    for i in range(0,len(New_state[1])):
        for j in range(0,len(New_state[1])):
            if state[i,j] == 0:
                if i == 2:
                    print("cannot perform Down movement")
                    return[0, state]
                    
                else:
                    print("Down movement performed")
                    New_state[i+1,j], New_state[i,j] = New_state[i,j], New_state[i+1,j]
                    return[1, New_state]
                
            
            
def AddNode(New_N):
    global a
    global b
    global flag 
    flag = 1
    
    for values in AllNodes.values():
        if (values == New_N).all():
            flag = 0
            print("present_do not add")
    
    if(flag == 1):
        print("Not present_do add")
        a = a+1
        AllNodes[a] = New_N
        ParentNodes[a] = b

            

def Check_and_Add(state1):
    global b
    global NewNode1
    global NewNode2
    global NewNode3
    global NewNode4
    [Status, NewNode] = ActionMoveLeft(state1)
    print(NewNode)
    AddNode(NewNode)
    print("")
    NewNode1 = NewNode.copy()
    
    [Status, NewNode] = ActionMoveUp(state1)
    print(NewNode)
    AddNode(NewNode)
    print("")
    NewNode2 = NewNode.copy()
    
    [Status, NewNode] = ActionMoveRight(state1)
    print(NewNode)
    AddNode(NewNode)
    print("")
    NewNode3 = NewNode.copy()
    
    [Status, NewNode] = ActionMoveDown(state1)
    print(NewNode)
    AddNode(NewNode)
    print("")
    print("Next Iteration")
    print("")
    NewNode4 = NewNode.copy()
    b = b+1
    
     

In [215]:
def get_key_AllNodes(val): 
    for key, value in AllNodes.items(): 
         if (val == value).all(): 
             return key 
  
    return "key doesn't exist"


def get_key_ParentNodes(val): 
    for key, value in ParentNodes.items(): 
         if (val == value): 
             return key 
  
    return "key doesn't exist"


def clean_AllNodes(AllNodes):
    key = get_key_AllNodes(Goal_Node)
    length = len(AllNodes)
    while(key != length):
        key = key + 1
        AllNodes.pop(key, None)

In [216]:
def generate_path(p_nodes):
    
    Start_key = get_key_AllNodes(Node_State) 
    print("Start_key =")
    print(Start_key)
    print("")

    Goal_key = get_key_AllNodes(Goal_Node)
    print("Goal_key = ")
    print(Goal_key)
    print("") 
    
    Goal = 0
    
    path.insert(Goal, Goal_key)
    print("goal_path = ")
    
    while(path[Goal] != Start_key):
        Goal = Goal + 1
        path.insert(Goal, p_nodes[Goal_key])
        Goal_key = p_nodes[Goal_key]      
    path.sort()
    print(path)
    return(path)


def print_optimalpath(path):
    print("Optinal path from Start to Goal")
    for m in path:
        
        print(AllNodes[m])
        print("")

    

In [235]:
while((not(np.array_equal(NewNode1, Goal_Node))) and (not(np.array_equal(NewNode2, Goal_Node))) and (not(np.array_equal(NewNode3, Goal_Node))) and (not(np.array_equal(NewNode4, Goal_Node)))):
    global next_node 
    Check_and_Add(AllNodes[next_node])
    next_node = next_node +1

left movement performed
[[0 1 2]
 [4 6 8]
 [7 3 5]]
Not present_do add

cannot perform Up movement
[[1 0 2]
 [4 6 8]
 [7 3 5]]
present_do not add

right movement performed
[[1 2 0]
 [4 6 8]
 [7 3 5]]
Not present_do add

Down movement performed
[[1 6 2]
 [4 0 8]
 [7 3 5]]
Not present_do add

Next Iteration

cannot perform left movement
[[0 1 2]
 [4 6 8]
 [7 3 5]]
present_do not add

cannot perform Up movement
[[0 1 2]
 [4 6 8]
 [7 3 5]]
present_do not add

right movement performed
[[1 0 2]
 [4 6 8]
 [7 3 5]]
present_do not add

Down movement performed
[[4 1 2]
 [0 6 8]
 [7 3 5]]
Not present_do add

Next Iteration

left movement performed
[[1 0 2]
 [4 6 8]
 [7 3 5]]
present_do not add

cannot perform Up movement
[[1 2 0]
 [4 6 8]
 [7 3 5]]
present_do not add

cannot perform Right movement
[[1 2 0]
 [4 6 8]
 [7 3 5]]
present_do not add

Down movement performed
[[1 2 8]
 [4 6 0]
 [7 3 5]]
Not present_do add

Next Iteration

left movement performed
[[1 6 2]
 [0 4 8]
 [7 3 5]]
Not present_do

left movement performed
[[4 1 2]
 [0 6 5]
 [7 8 3]]
Not present_do add

up movement performed
[[4 0 2]
 [6 1 5]
 [7 8 3]]
Not present_do add

right movement performed
[[4 1 2]
 [6 5 0]
 [7 8 3]]
Not present_do add

Down movement performed
[[4 1 2]
 [6 8 5]
 [7 0 3]]
present_do not add

Next Iteration

cannot perform left movement
[[0 1 2]
 [4 3 8]
 [6 7 5]]
present_do not add

cannot perform Up movement
[[0 1 2]
 [4 3 8]
 [6 7 5]]
present_do not add

right movement performed
[[1 0 2]
 [4 3 8]
 [6 7 5]]
Not present_do add

Down movement performed
[[4 1 2]
 [0 3 8]
 [6 7 5]]
present_do not add

Next Iteration

left movement performed
[[4 1 2]
 [0 3 8]
 [6 7 5]]
present_do not add

up movement performed
[[4 0 2]
 [3 1 8]
 [6 7 5]]
Not present_do add

right movement performed
[[4 1 2]
 [3 8 0]
 [6 7 5]]
Not present_do add

Down movement performed
[[4 1 2]
 [3 7 8]
 [6 0 5]]
Not present_do add

Next Iteration

left movement performed
[[4 1 2]
 [0 6 3]
 [7 5 8]]
Not present_do add

up moveme

present_do not add

right movement performed
[[1 0 2]
 [4 6 3]
 [7 5 8]]
present_do not add

Down movement performed
[[4 1 2]
 [0 6 3]
 [7 5 8]]
present_do not add

Next Iteration

left movement performed
[[1 0 2]
 [4 6 3]
 [7 5 8]]
present_do not add

cannot perform Up movement
[[1 2 0]
 [4 6 3]
 [7 5 8]]
present_do not add

cannot perform Right movement
[[1 2 0]
 [4 6 3]
 [7 5 8]]
present_do not add

Down movement performed
[[1 2 3]
 [4 6 0]
 [7 5 8]]
Not present_do add

Next Iteration

cannot perform left movement
[[1 6 2]
 [4 5 3]
 [0 7 8]]
present_do not add

up movement performed
[[1 6 2]
 [0 5 3]
 [4 7 8]]
Not present_do add

right movement performed
[[1 6 2]
 [4 5 3]
 [7 0 8]]
present_do not add

cannot perform Down movement
[[1 6 2]
 [4 5 3]
 [0 7 8]]
present_do not add

Next Iteration

cannot perform left movement
[[0 1 6]
 [4 3 2]
 [7 5 8]]
present_do not add

cannot perform Up movement
[[0 1 6]
 [4 3 2]
 [7 5 8]]
present_do not add

right movement performed
[[1 0 6]
 [4 3 2

Not present_do add

Next Iteration

left movement performed
[[1 2 8]
 [6 7 5]
 [0 4 3]]
Not present_do add

up movement performed
[[1 2 8]
 [6 0 5]
 [4 7 3]]
present_do not add

right movement performed
[[1 2 8]
 [6 7 5]
 [4 3 0]]
Not present_do add

cannot perform Down movement
[[1 2 8]
 [6 7 5]
 [4 0 3]]
present_do not add

Next Iteration

left movement performed
[[0 2 8]
 [1 4 5]
 [7 6 3]]
present_do not add

cannot perform Up movement
[[2 0 8]
 [1 4 5]
 [7 6 3]]
present_do not add

right movement performed
[[2 8 0]
 [1 4 5]
 [7 6 3]]
Not present_do add

Down movement performed
[[2 4 8]
 [1 0 5]
 [7 6 3]]
Not present_do add

Next Iteration

left movement performed
[[1 2 8]
 [7 4 5]
 [0 6 3]]
present_do not add

up movement performed
[[1 2 8]
 [7 0 5]
 [6 4 3]]
Not present_do add

right movement performed
[[1 2 8]
 [7 4 5]
 [6 3 0]]
Not present_do add

cannot perform Down movement
[[1 2 8]
 [7 4 5]
 [6 0 3]]
present_do not add

Next Iteration

cannot perform left movement
[[4 1 8]
 [


Next Iteration

left movement performed
[[1 6 2]
 [7 4 3]
 [0 5 8]]
present_do not add

up movement performed
[[1 6 2]
 [7 0 3]
 [5 4 8]]
Not present_do add

right movement performed
[[1 6 2]
 [7 4 3]
 [5 8 0]]
Not present_do add

cannot perform Down movement
[[1 6 2]
 [7 4 3]
 [5 0 8]]
present_do not add

Next Iteration

left movement performed
[[1 2 3]
 [4 0 6]
 [7 5 8]]
Not present_do add

up movement performed
[[1 2 0]
 [4 6 3]
 [7 5 8]]
present_do not add

cannot perform Right movement
[[1 2 3]
 [4 6 0]
 [7 5 8]]
present_do not add

Down movement performed
[[1 2 3]
 [4 6 8]
 [7 5 0]]
Not present_do add

Next Iteration

cannot perform left movement
[[1 6 2]
 [0 5 3]
 [4 7 8]]
present_do not add

up movement performed
[[0 6 2]
 [1 5 3]
 [4 7 8]]
Not present_do add

right movement performed
[[1 6 2]
 [5 0 3]
 [4 7 8]]
Not present_do add

Down movement performed
[[1 6 2]
 [4 5 3]
 [0 7 8]]
present_do not add

Next Iteration

cannot perform left movement
[[4 1 6]
 [0 3 2]
 [7 5 8]]
pr


left movement performed
[[4 3 1]
 [0 6 2]
 [7 5 8]]
Not present_do add

up movement performed
[[4 0 1]
 [6 3 2]
 [7 5 8]]
present_do not add

right movement performed
[[4 3 1]
 [6 2 0]
 [7 5 8]]
Not present_do add

Down movement performed
[[4 3 1]
 [6 5 2]
 [7 0 8]]
Not present_do add

Next Iteration

left movement performed
[[1 0 2]
 [4 7 8]
 [3 6 5]]
present_do not add

cannot perform Up movement
[[1 2 0]
 [4 7 8]
 [3 6 5]]
present_do not add

cannot perform Right movement
[[1 2 0]
 [4 7 8]
 [3 6 5]]
present_do not add

Down movement performed
[[1 2 8]
 [4 7 0]
 [3 6 5]]
Not present_do add

Next Iteration

left movement performed
[[1 7 2]
 [0 4 8]
 [3 6 5]]
Not present_do add

up movement performed
[[1 0 2]
 [4 7 8]
 [3 6 5]]
present_do not add

right movement performed
[[1 7 2]
 [4 8 0]
 [3 6 5]]
Not present_do add

Down movement performed
[[1 7 2]
 [4 6 8]
 [3 0 5]]
Not present_do add

Next Iteration

left movement performed
[[7 4 2]
 [0 1 8]
 [3 6 5]]
present_do not add

up movem

Not present_do add

up movement performed
[[4 1 8]
 [2 6 0]
 [7 3 5]]
present_do not add

cannot perform Right movement
[[4 1 8]
 [2 6 5]
 [7 3 0]]
present_do not add

cannot perform Down movement
[[4 1 8]
 [2 6 5]
 [7 3 0]]
present_do not add

Next Iteration

cannot perform left movement
[[4 1 8]
 [2 3 6]
 [0 7 5]]
present_do not add

up movement performed
[[4 1 8]
 [0 3 6]
 [2 7 5]]
Not present_do add

right movement performed
[[4 1 8]
 [2 3 6]
 [7 0 5]]
present_do not add

cannot perform Down movement
[[4 1 8]
 [2 3 6]
 [0 7 5]]
present_do not add

Next Iteration

left movement performed
[[4 1 8]
 [2 3 6]
 [7 0 5]]
present_do not add

up movement performed
[[4 1 8]
 [2 3 0]
 [7 5 6]]
Not present_do add

cannot perform Right movement
[[4 1 8]
 [2 3 6]
 [7 5 0]]
present_do not add

cannot perform Down movement
[[4 1 8]
 [2 3 6]
 [7 5 0]]
present_do not add

Next Iteration

left movement performed
[[4 1 8]
 [0 7 6]
 [3 2 5]]
Not present_do add

up movement performed
[[4 0 8]
 [7 1 6]
 


cannot perform Right movement
[[1 8 5]
 [4 2 3]
 [7 6 0]]
present_do not add

cannot perform Down movement
[[1 8 5]
 [4 2 3]
 [7 6 0]]
present_do not add

Next Iteration

cannot perform left movement
[[0 1 2]
 [4 5 8]
 [7 6 3]]
present_do not add

cannot perform Up movement
[[0 1 2]
 [4 5 8]
 [7 6 3]]
present_do not add

right movement performed
[[1 0 2]
 [4 5 8]
 [7 6 3]]
present_do not add

Down movement performed
[[4 1 2]
 [0 5 8]
 [7 6 3]]
Not present_do add

Next Iteration

left movement performed
[[1 5 2]
 [0 4 8]
 [7 6 3]]
Not present_do add

up movement performed
[[1 0 2]
 [4 5 8]
 [7 6 3]]
present_do not add

right movement performed
[[1 5 2]
 [4 8 0]
 [7 6 3]]
Not present_do add

Down movement performed
[[1 5 2]
 [4 6 8]
 [7 0 3]]
Not present_do add

Next Iteration

cannot perform left movement
[[0 2 8]
 [6 1 4]
 [7 3 5]]
present_do not add

cannot perform Up movement
[[0 2 8]
 [6 1 4]
 [7 3 5]]
present_do not add

right movement performed
[[2 0 8]
 [6 1 4]
 [7 3 5]]
Not pre


cannot perform Right movement
[[4 6 0]
 [8 1 2]
 [7 3 5]]
present_do not add

Down movement performed
[[4 6 2]
 [8 1 0]
 [7 3 5]]
Not present_do add

Next Iteration

left movement performed
[[4 0 1]
 [8 2 6]
 [7 3 5]]
Not present_do add

cannot perform Up movement
[[4 1 0]
 [8 2 6]
 [7 3 5]]
present_do not add

cannot perform Right movement
[[4 1 0]
 [8 2 6]
 [7 3 5]]
present_do not add

Down movement performed
[[4 1 6]
 [8 2 0]
 [7 3 5]]
present_do not add

Next Iteration

left movement performed
[[4 1 6]
 [8 2 5]
 [7 0 3]]
Not present_do add

up movement performed
[[4 1 6]
 [8 2 0]
 [7 3 5]]
present_do not add

cannot perform Right movement
[[4 1 6]
 [8 2 5]
 [7 3 0]]
present_do not add

cannot perform Down movement
[[4 1 6]
 [8 2 5]
 [7 3 0]]
present_do not add

Next Iteration

cannot perform left movement
[[4 1 6]
 [8 3 2]
 [0 7 5]]
present_do not add

up movement performed
[[4 1 6]
 [0 3 2]
 [8 7 5]]
Not present_do add

right movement performed
[[4 1 6]
 [8 3 2]
 [7 0 5]]
present

right movement performed
[[6 2 8]
 [1 3 0]
 [4 7 5]]
present_do not add

Down movement performed
[[6 2 8]
 [1 7 3]
 [4 0 5]]
Not present_do add

Next Iteration

left movement performed
[[6 2 8]
 [1 3 5]
 [4 0 7]]
Not present_do add

up movement performed
[[6 2 8]
 [1 3 0]
 [4 7 5]]
present_do not add

cannot perform Right movement
[[6 2 8]
 [1 3 5]
 [4 7 0]]
present_do not add

cannot perform Down movement
[[6 2 8]
 [1 3 5]
 [4 7 0]]
present_do not add

Next Iteration

cannot perform left movement
[[0 3 2]
 [6 1 8]
 [4 7 5]]
present_do not add

cannot perform Up movement
[[0 3 2]
 [6 1 8]
 [4 7 5]]
present_do not add

right movement performed
[[3 0 2]
 [6 1 8]
 [4 7 5]]
Not present_do add

Down movement performed
[[6 3 2]
 [0 1 8]
 [4 7 5]]
present_do not add

Next Iteration

cannot perform left movement
[[6 3 2]
 [4 1 8]
 [0 7 5]]
present_do not add

up movement performed
[[6 3 2]
 [0 1 8]
 [4 7 5]]
present_do not add

right movement performed
[[6 3 2]
 [4 1 8]
 [7 0 5]]
Not present_d

 [7 8 2]]
Not present_do add

cannot perform Right movement
[[1 3 6]
 [4 5 2]
 [7 8 0]]
present_do not add

cannot perform Down movement
[[1 3 6]
 [4 5 2]
 [7 8 0]]
present_do not add

Next Iteration

cannot perform left movement
[[6 4 2]
 [0 7 8]
 [3 1 5]]
present_do not add

up movement performed
[[0 4 2]
 [6 7 8]
 [3 1 5]]
Not present_do add

right movement performed
[[6 4 2]
 [7 0 8]
 [3 1 5]]
present_do not add

Down movement performed
[[6 4 2]
 [3 7 8]
 [0 1 5]]
Not present_do add

Next Iteration

left movement performed
[[0 6 2]
 [7 4 8]
 [3 1 5]]
Not present_do add

cannot perform Up movement
[[6 0 2]
 [7 4 8]
 [3 1 5]]
present_do not add

right movement performed
[[6 2 0]
 [7 4 8]
 [3 1 5]]
Not present_do add

Down movement performed
[[6 4 2]
 [7 0 8]
 [3 1 5]]
present_do not add

Next Iteration

left movement performed
[[6 4 2]
 [7 0 8]
 [3 1 5]]
present_do not add

up movement performed
[[6 4 0]
 [7 8 2]
 [3 1 5]]
Not present_do add

cannot perform Right movement
[[6 4 2]
 [


cannot perform Right movement
[[1 2 8]
 [4 7 0]
 [3 6 5]]
present_do not add

Down movement performed
[[1 2 8]
 [4 7 5]
 [3 6 0]]
Not present_do add

Next Iteration

cannot perform left movement
[[1 7 2]
 [0 4 8]
 [3 6 5]]
present_do not add

up movement performed
[[0 7 2]
 [1 4 8]
 [3 6 5]]
Not present_do add

right movement performed
[[1 7 2]
 [4 0 8]
 [3 6 5]]
present_do not add

Down movement performed
[[1 7 2]
 [3 4 8]
 [0 6 5]]
Not present_do add

Next Iteration

left movement performed
[[1 7 2]
 [4 0 8]
 [3 6 5]]
present_do not add

up movement performed
[[1 7 0]
 [4 8 2]
 [3 6 5]]
Not present_do add

cannot perform Right movement
[[1 7 2]
 [4 8 0]
 [3 6 5]]
present_do not add

Down movement performed
[[1 7 2]
 [4 8 5]
 [3 6 0]]
Not present_do add

Next Iteration

left movement performed
[[1 7 2]
 [4 6 8]
 [0 3 5]]
Not present_do add

up movement performed
[[1 7 2]
 [4 0 8]
 [3 6 5]]
present_do not add

right movement performed
[[1 7 2]
 [4 6 8]
 [3 5 0]]
Not present_do add

ca

Not present_do add

Down movement performed
[[2 8 6]
 [1 0 4]
 [7 3 5]]
present_do not add

Next Iteration

left movement performed
[[2 8 6]
 [1 3 4]
 [0 7 5]]
Not present_do add

up movement performed
[[2 8 6]
 [1 0 4]
 [7 3 5]]
present_do not add

right movement performed
[[2 8 6]
 [1 3 4]
 [7 5 0]]
Not present_do add

cannot perform Down movement
[[2 8 6]
 [1 3 4]
 [7 0 5]]
present_do not add

Next Iteration

left movement performed
[[2 8 6]
 [1 4 5]
 [0 7 3]]
Not present_do add

up movement performed
[[2 8 6]
 [1 0 5]
 [7 4 3]]
Not present_do add

right movement performed
[[2 8 6]
 [1 4 5]
 [7 3 0]]
present_do not add

cannot perform Down movement
[[2 8 6]
 [1 4 5]
 [7 0 3]]
present_do not add

Next Iteration

left movement performed
[[2 4 8]
 [7 1 6]
 [0 3 5]]
present_do not add

up movement performed
[[2 4 8]
 [7 0 6]
 [3 1 5]]
Not present_do add

right movement performed
[[2 4 8]
 [7 1 6]
 [3 5 0]]
Not present_do add

cannot perform Down movement
[[2 4 8]
 [7 1 6]
 [3 0 5]]
pres


Next Iteration

left movement performed
[[1 8 6]
 [4 0 5]
 [7 2 3]]
present_do not add

up movement performed
[[1 8 0]
 [4 5 6]
 [7 2 3]]
Not present_do add

cannot perform Right movement
[[1 8 6]
 [4 5 0]
 [7 2 3]]
present_do not add

Down movement performed
[[1 8 6]
 [4 5 3]
 [7 2 0]]
Not present_do add

Next Iteration

left movement performed
[[2 8 6]
 [1 0 3]
 [4 7 5]]
Not present_do add

up movement performed
[[2 8 0]
 [1 3 6]
 [4 7 5]]
present_do not add

cannot perform Right movement
[[2 8 6]
 [1 3 0]
 [4 7 5]]
present_do not add

Down movement performed
[[2 8 6]
 [1 3 5]
 [4 7 0]]
Not present_do add

Next Iteration

cannot perform left movement
[[2 3 8]
 [0 1 6]
 [4 7 5]]
present_do not add

up movement performed
[[0 3 8]
 [2 1 6]
 [4 7 5]]
Not present_do add

right movement performed
[[2 3 8]
 [1 0 6]
 [4 7 5]]
present_do not add

Down movement performed
[[2 3 8]
 [4 1 6]
 [0 7 5]]
Not present_do add

Next Iteration

left movement performed
[[2 3 8]
 [1 0 6]
 [4 7 5]]
present


Next Iteration

cannot perform left movement
[[6 2 8]
 [0 4 5]
 [1 7 3]]
present_do not add

up movement performed
[[0 2 8]
 [6 4 5]
 [1 7 3]]
Not present_do add

right movement performed
[[6 2 8]
 [4 0 5]
 [1 7 3]]
Not present_do add

Down movement performed
[[6 2 8]
 [1 4 5]
 [0 7 3]]
present_do not add

Next Iteration

cannot perform left movement
[[6 2 8]
 [0 1 5]
 [7 4 3]]
present_do not add

up movement performed
[[0 2 8]
 [6 1 5]
 [7 4 3]]
Not present_do add

right movement performed
[[6 2 8]
 [1 0 5]
 [7 4 3]]
present_do not add

Down movement performed
[[6 2 8]
 [7 1 5]
 [0 4 3]]
Not present_do add

Next Iteration

left movement performed
[[0 6 8]
 [1 2 5]
 [7 4 3]]
Not present_do add

cannot perform Up movement
[[6 0 8]
 [1 2 5]
 [7 4 3]]
present_do not add

right movement performed
[[6 8 0]
 [1 2 5]
 [7 4 3]]
Not present_do add

Down movement performed
[[6 2 8]
 [1 0 5]
 [7 4 3]]
present_do not add

Next Iteration

left movement performed
[[6 2 8]
 [1 0 5]
 [7 4 3]]
present

left movement performed
[[4 1 6]
 [8 2 5]
 [0 7 3]]
Not present_do add

up movement performed
[[4 1 6]
 [8 0 5]
 [7 2 3]]
Not present_do add

right movement performed
[[4 1 6]
 [8 2 5]
 [7 3 0]]
present_do not add

cannot perform Down movement
[[4 1 6]
 [8 2 5]
 [7 0 3]]
present_do not add

Next Iteration

cannot perform left movement
[[4 1 6]
 [0 3 2]
 [8 7 5]]
present_do not add

up movement performed
[[0 1 6]
 [4 3 2]
 [8 7 5]]
Not present_do add

right movement performed
[[4 1 6]
 [3 0 2]
 [8 7 5]]
Not present_do add

Down movement performed
[[4 1 6]
 [8 3 2]
 [0 7 5]]
present_do not add

Next Iteration

left movement performed
[[4 1 6]
 [8 0 3]
 [7 5 2]]
Not present_do add

up movement performed
[[4 1 0]
 [8 3 6]
 [7 5 2]]
Not present_do add

cannot perform Right movement
[[4 1 6]
 [8 3 0]
 [7 5 2]]
present_do not add

Down movement performed
[[4 1 6]
 [8 3 2]
 [7 5 0]]
present_do not add

Next Iteration

cannot perform left movement
[[4 1 6]
 [0 7 2]
 [3 8 5]]
present_do not add



cannot perform Down movement
[[6 2 8]
 [1 3 5]
 [4 0 7]]
present_do not add

Next Iteration

left movement performed
[[0 3 2]
 [6 1 8]
 [4 7 5]]
present_do not add

cannot perform Up movement
[[3 0 2]
 [6 1 8]
 [4 7 5]]
present_do not add

right movement performed
[[3 2 0]
 [6 1 8]
 [4 7 5]]
Not present_do add

Down movement performed
[[3 1 2]
 [6 0 8]
 [4 7 5]]
present_do not add

Next Iteration

left movement performed
[[6 3 2]
 [4 1 8]
 [0 7 5]]
present_do not add

up movement performed
[[6 3 2]
 [4 0 8]
 [7 1 5]]
Not present_do add

right movement performed
[[6 3 2]
 [4 1 8]
 [7 5 0]]
Not present_do add

cannot perform Down movement
[[6 3 2]
 [4 1 8]
 [7 0 5]]
present_do not add

Next Iteration

left movement performed
[[0 6 3]
 [1 8 2]
 [4 7 5]]
Not present_do add

cannot perform Up movement
[[6 0 3]
 [1 8 2]
 [4 7 5]]
present_do not add

right movement performed
[[6 3 0]
 [1 8 2]
 [4 7 5]]
present_do not add

Down movement performed
[[6 8 3]
 [1 0 2]
 [4 7 5]]
Not present_do add

In [236]:
clean_AllNodes(AllNodes)

In [237]:
print(ParentNodes)

{1: 0, 2: 1, 3: 1, 4: 1, 5: 2, 6: 3, 7: 4, 8: 4, 9: 4, 10: 5, 11: 5, 12: 6, 13: 6, 14: 7, 15: 7, 16: 8, 17: 8, 18: 9, 19: 9, 20: 10, 21: 10, 22: 10, 23: 11, 24: 12, 25: 12, 26: 12, 27: 13, 28: 14, 29: 15, 30: 16, 31: 17, 32: 18, 33: 19, 34: 20, 35: 20, 36: 21, 37: 21, 38: 22, 39: 22, 40: 23, 41: 23, 42: 24, 43: 24, 44: 25, 45: 25, 46: 26, 47: 26, 48: 27, 49: 27, 50: 28, 51: 28, 52: 29, 53: 29, 54: 30, 55: 30, 56: 31, 57: 31, 58: 32, 59: 32, 60: 33, 61: 33, 62: 34, 63: 35, 64: 36, 65: 37, 66: 38, 67: 39, 68: 40, 69: 40, 70: 40, 71: 41, 72: 42, 73: 43, 74: 44, 75: 45, 76: 46, 77: 47, 78: 48, 79: 49, 80: 49, 81: 49, 82: 50, 83: 51, 84: 51, 85: 52, 86: 52, 87: 52, 88: 53, 89: 54, 90: 55, 91: 55, 92: 56, 93: 57, 94: 57, 95: 57, 96: 58, 97: 59, 98: 59, 99: 59, 100: 60, 101: 60, 102: 60, 103: 61, 104: 62, 105: 63, 106: 63, 107: 64, 108: 64, 109: 65, 110: 65, 111: 66, 112: 66, 113: 67, 114: 67, 115: 68, 116: 68, 117: 69, 118: 69, 119: 70, 120: 70, 121: 71, 122: 71, 123: 72, 124: 72, 125: 73, 1

In [238]:
print(AllNodes)


{1: array([[1, 0, 2],
       [4, 6, 8],
       [7, 3, 5]]), 2: array([[0, 1, 2],
       [4, 6, 8],
       [7, 3, 5]]), 3: array([[1, 2, 0],
       [4, 6, 8],
       [7, 3, 5]]), 4: array([[1, 6, 2],
       [4, 0, 8],
       [7, 3, 5]]), 5: array([[4, 1, 2],
       [0, 6, 8],
       [7, 3, 5]]), 6: array([[1, 2, 8],
       [4, 6, 0],
       [7, 3, 5]]), 7: array([[1, 6, 2],
       [0, 4, 8],
       [7, 3, 5]]), 8: array([[1, 6, 2],
       [4, 8, 0],
       [7, 3, 5]]), 9: array([[1, 6, 2],
       [4, 3, 8],
       [7, 0, 5]]), 10: array([[4, 1, 2],
       [6, 0, 8],
       [7, 3, 5]]), 11: array([[4, 1, 2],
       [7, 6, 8],
       [0, 3, 5]]), 12: array([[1, 2, 8],
       [4, 0, 6],
       [7, 3, 5]]), 13: array([[1, 2, 8],
       [4, 6, 5],
       [7, 3, 0]]), 14: array([[0, 6, 2],
       [1, 4, 8],
       [7, 3, 5]]), 15: array([[1, 6, 2],
       [7, 4, 8],
       [0, 3, 5]]), 16: array([[1, 6, 0],
       [4, 8, 2],
       [7, 3, 5]]), 17: array([[1, 6, 2],
       [4, 8, 5],
       [

In [239]:
goal_path = generate_path(ParentNodes)


Start_key =
1

Goal_key = 
1268

goal_path = 
[1, 4, 9, 19, 33, 60, 101, 180, 286, 482, 757, 1268]


In [240]:
print_optimalpath(goal_path)


Optinal path from Start to Goal
[[1 0 2]
 [4 6 8]
 [7 3 5]]

[[1 6 2]
 [4 0 8]
 [7 3 5]]

[[1 6 2]
 [4 3 8]
 [7 0 5]]

[[1 6 2]
 [4 3 8]
 [7 5 0]]

[[1 6 2]
 [4 3 0]
 [7 5 8]]

[[1 6 2]
 [4 0 3]
 [7 5 8]]

[[1 0 2]
 [4 6 3]
 [7 5 8]]

[[1 2 0]
 [4 6 3]
 [7 5 8]]

[[1 2 3]
 [4 6 0]
 [7 5 8]]

[[1 2 3]
 [4 0 6]
 [7 5 8]]

[[1 2 3]
 [4 5 6]
 [7 0 8]]

[[1 2 3]
 [4 5 6]
 [7 8 0]]

